name: smged
description: "Sistema multiplataforma para la gestion de estudiantes con discapacidad."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.8.1
  data_table_2: ^2.5.11
  intl: ^0.19.0
  shared_preferences: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
