name: smged
description: "Sistema multiplataforma para la gestion de estudiantes con discapacidad."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.8.1
  data_table_2: ^2.5.11
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  pdf: ^3.11.0 
  printing: ^5.14.0 
  path_provider: ^2.1.4 
  url_launcher: ^6.1.0
  file_picker: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
  assets:
    - icon/smged_Logo.png